### ISSUE TITLE
Is it possibile to hide the alpha slider?

### ISSUE THREAD

**Issue by Rainer-Lang** [martin-stone/hsv-alpha-color-picker-android#1]

**Comment by martin-stone** [comment]
It is now, in version 1.1.0 :-)

**Comment by Rainer-Lang** [comment]
Thanks, I will try it.

**Comment by Rainer-Lang** [comment]
Tested and all is fine. Thanks.

Just an idea: Is it possible to put the view also in a dialogfragment and deliver this with/in your lib?

**Comment by martin-stone** [comment]
Should be possible. I'm happy to receive pull requests :-)
