### ISSUE TITLE
Broken layout on small screen

### ISSUE THREAD

**Issue by ckhmer1** [martin-stone/hsv-alpha-color-picker-android#11]
Hi,
thanks for the beautifull color picker preference.
Unfortunately it is not working well for small screen.
See the attached screenshot from the Color Picker Demo. 
The ValueView is shown partially and the AlphaView and the EditText are not shown at all.
![device-2015-09-26-103505](https://cloud.githubusercontent.com/assets/2863760/10116636/67a0ead2-643a-11e5-95d3-a5f6567436ee.png)

**Comment by martin-stone** [comment]
Yes, that's not ideal. I'll look into it.

**Comment by martin-stone** [comment]
I've pushed a fix for this to the repo, but not yet released it on jcenter. If you're building from source getting the latest should fix it.

**Comment by martin-stone** [comment]
Update: The fix is now available on JCenter in version 1.4.0. Thanks for reporting the bug.
