### ISSUE TITLE
OnPreferenceChangeListener is not called

### ISSUE THREAD

**Issue by ganping** [martin-stone/hsv-alpha-color-picker-android#13]
The OnPreferenceChangeListener is not triggered when a color is selected.

My current work around is to implement SharedPreferences.OnSharedPreferenceChangeListener in my PreferenceFragment and check the returned key.

**Comment by ganping** [comment]
One solution I can think of is override onDialogClosed() and trigger callChangeListener(value) when positiveResult is true.

**Comment by martin-stone** [comment]
Fixed in version 1.5.1.
