### ISSUE TITLE
Summary text problem

### ISSUE THREAD

**Issue by baldapps** [martin-stone/hsv-alpha-color-picker-android#15]
It seems impossible to set a summary text for your color preference. I'm using api 23.

**Comment by martin-stone** [comment]
Is this on a ColorPreference that also has a `colorpicker_noneSelectedSummaryText` value? I can reproduce the problem in that case (and see why it happens) but it behaves correctly for me if `colorpicker_noneSelectedSummaryText` is not being used. Can you confirm this?

**Comment by baldapps** [comment]
Yes, I can confirm

**Comment by martin-stone** [comment]
Fixed in version 1.5.2
