### ISSUE TITLE
Cannot acquire colors when called setPickerCount(n); where n>1

### ISSUE THREAD

**Issue by smedic** [martin-stone/hsv-alpha-color-picker-android#19]
When trying to set multiple colors by using ColorPickerDialogBuilder, for instance: text color and background color, I cannot acquire set colors.

```
.setPositiveButton("ok", new ColorPickerClickListener() {
                @Override
                public void onClick(DialogInterface dialog, int selectedColor, Integer[] allColors) {
                       //how to get chosen colors?
                }
})

```

 I can get selectedColor, but how to know  which index is that? Is that 1st color, 2nd etc.

**Comment by martin-stone** [comment]
I think you've submitted this bug in the wrong repo. I don't recognise those classes and functions. This library doesn't work like that.

**Comment by smedic** [comment]
True, my mistake. Sorry. Remove this
