### ISSUE TITLE
Soft keyboard popups by default

### ISSUE THREAD

**Issue by aloz77** [martin-stone/hsv-alpha-color-picker-android#27]
Great lib. However in Android 6 the soft keyboard popups when opening com.rarepebble.colorpicker.ColorPreference as the hex field is gaining focus. Is there a way to avoid keyboard?

**Comment by martin-stone** [comment]
I can't reproduce this. For me the hex field has focus but the keyboard doesn't show until I tap on it. I'm running the demo app on the emulator at API 23.

What device are you seeing this on? Is it running stock Android?

**Comment by aloz77** [comment]
I can reproduce the issue with Demo app on stock Android 6.0.1 on Nexus 7 and standard keyboard. The keyboard is popping up if the hex field is enabled.

**Comment by martin-stone** [comment]
Thanks: Reproduced in a Nexus 7 emulator and the latest release (2.0.1) fixes it for me. Can you confirm that it solves it for you?

**Comment by aloz77** [comment]
Thank your, looks much better. There is no keyboard popping up. When tapping on the hex field the fullscreen editor opens for the value. You could probably improve it by adding android:imeOptions="flagNoExtractUi" to the edittext view.

**Comment by martin-stone** [comment]
Again, I'm not getting the full-screen editor, but it's easy enough for me to add the flag. I'll include that in the next release.

**Comment by MPArnold** [comment]
After the _AndroidX_ implementation the soft keyboard again started popping up by default on **my clone**. 
For what it's worth, I added this to the end of **ColorPreferenceFragment.java** ...

```
@NonNull
@Override
/** [ Hide the soft keyboard after accessing the dialog ] */
public Dialog onCreateDialog(Bundle savedInstanceState) {
    Dialog dialog = super.onCreateDialog(savedInstanceState);
    Window window = dialog.getWindow();
    window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_HIDDEN);
    return dialog;
}
```

Beautiful color picker by the way! Any special instructions on crediting the author?
