### ISSUE TITLE
Change the colorPrimary

### ISSUE THREAD

**Issue by RujjhidHD** [martin-stone/hsv-alpha-color-picker-android#29]
Hello, i want to change the _colorPrimary_ with the ColorPicker _(values/styles.xml)_ . This is posible? If yes, can you explain me a little? Actually i have this system in my MainActivity.java and choose the theme via PreferenceScreen

`final boolean Orange = Theme.getInstance(this).setTheme().equals("Orange");

boolean mCreatingActivity = true;
        if (!mCreatingActivity) {
            if (Orange)
                setTheme(R.style.Orange);`

**Comment by martin-stone** [comment]
If you can change it programmatically then you can do what you like with the value that the color picker sets. However it looks like [you can't change colorPrimary dynamically](http://stackoverflow.com/questions/25815769/how-to-really-programmatically-change-primary-and-accent-color-in-android-loll).
