### ISSUE TITLE
Compatibility upto API 14

### ISSUE THREAD

**Issue by AkshayChordiya** [martin-stone/hsv-alpha-color-picker-android#3]
Excellent library, it's just what I needed but can you make your library backward compatible to API 14, moreover my project supports API 14.

Waiting for it.

**Comment by AkshayChordiya** [comment]
Any status?

**Comment by martin-stone** [comment]
Hi. I haven't had a chance to look at this yet. It's possible that it will work already and just needs the _minSdkVersion_ changing in the build.gradle. 

If you want to speed things up, you could try building the library locally and changing the _minSdkVersion_ and see if anything breaks.

**Comment by AkshayChordiya** [comment]
@martin-stone 
Well thanks for the tip. I got to find how to build library locally

**Comment by martin-stone** [comment]
I've now had time to look at this and I've reduced the _minSdkVersion_ to 11. You only need to change the library dependency to 

```
compile 'com.rarepebble:colorpicker:1.2.0'.
```

**Comment by AkshayChordiya** [comment]
That's so cool.
Thank you.

Regards,
Akshay Chordiya
