### ISSUE TITLE
More documentation on direct usage of ColorPickerView

### ISSUE THREAD

**Issue by AkshayChordiya** [martin-stone/hsv-alpha-color-picker-android#4]
Hi @martin-stone 

I'm using try to use `ColorPickerView` directly inside a `Dialog` specifically `AlertDialog` but the view doesn't look like the one shown in the screenshot on main page.

P.S: I like your library & I appreciate your work.

**Comment by AkshayChordiya** [comment]
@martin-stone 
Extremely sorry I fixed it easily.

**Comment by Rainer-Lang** [comment]
Maybe you could share your solution.  :smiley:

**Comment by AkshayChordiya** [comment]
@Rainer-Lang 
Oh yeah sure, thanks for reminding.
1. Create a `Dialog` & add the following code:

```
View view = GET_YOUR_DIALOG_VIEW
colorPickerView = (ColorPickerView) view.findViewById(R.id.colorPicker);
colorPickerView.setColor(YOUR_COLOR);
colorPickerView.showAlpha(true);
colorPickerView.showHex(true);
```
1. Set custom view layout to `Dialog`

```
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.rarepebble.colorpicker.ColorPickerView
        android:id="@+id/colorPicker"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"/>

</FrameLayout>
```

**Comment by Rainer-Lang** [comment]
Thanks. 
The color dialog is really big. How about scrolling (older devices)? Put in a scrollview? 
How about making a pr? ;-)

**Comment by AkshayChordiya** [comment]
@Rainer-Lang 
Actually I didn't need a `ScrollView` so I didn't use it. You can add it as root element in the above example.
I'd love to PR but my code is based on upon 3rd Party `Dialog` library

**Comment by Rainer-Lang** [comment]
I use also a lib - material-dialogs.

**Comment by AkshayChordiya** [comment]
@Rainer-Lang 
Cool.
Here's the complete code for `Dialog` side

```
MaterialDialog dialog = new MaterialDialog.Builder(getActivity())
                .title(YOUR_TITLE)
                .positiveText(android.R.string.ok)
                .negativeText(android.R.string.cancel)
                .callback(new MaterialDialog.ButtonCallback() {
                    @Override
                    public void onPositive(MaterialDialog dialog) {
                        super.onPositive(dialog);
                        // Save color here
                        // Reflect the color on UI
                    }
                })
                .customView(THE_LAYOUT_MENTIONED_ABOVE, false)
                .build();

        View view = dialog.getCustomView();
        colorPickerView = (ColorPickerView) view.findViewById(R.id.colorPicker);
        colorPickerView.setColor(YOUR_COLOR);
        colorPickerView.showAlpha(true);
        colorPickerView.showHex(true);
```

I hope this helps you

**Comment by Rainer-Lang** [comment]
@AkshayChordiya WOW cool. :-)
I also have a button for neutral="select no color".
But I have a problem with scrolling this custom view in material-dialogs. Aidan said, that the material-dialogs are ok and the problem should be searched in the custom view. The height isn't calculated properly. I don't know - I haven't found anything... :-(

**Comment by AkshayChordiya** [comment]
@martin-stone 
I feel you copy the code which I pasted above, I mean the `MaterialDialog` code & then tweak the Layout by wrapping the `Views` inside with a `ScollView`
This should give you the functionality which you require.

**Comment by Rainer-Lang** [comment]
@AkshayChordiya Do you think this would help? This would be really awesome! :-)

**Comment by AkshayChordiya** [comment]
@Rainer-Lang 
It should help

**Comment by davewiard** [comment]
I am trying to use HSV-Alpha within a support-v4 DialogFragment. I am able to instantiate the dialog and inflate the view correctly but I have no positive/negative buttons and no "no color" button. It makes no difference whether I am in portrait or landscape mode. I don't believe the buttons are falling off the bottom of the visible area, either. If I take away hex and alpha the dialog height shrinks accordingly but I still see no buttons. I also installed on a physical device with more screen real estate than the emulator and they don't don't show there, either, despite a sizable percentage of screen available outside the dialog fragment. Both the emulator and phone are running Lollipop (5.0.1 and 5.1). My code is nearly verbatim copy/paste from the "Usage" section. Is there something I need to do to get the buttons to show up?
