### ISSUE TITLE
After hex value is deleted, color changes to transparent even though colorpicker_showAlpha is set to false

### ISSUE THREAD

**Issue by clearpath** [martin-stone/hsv-alpha-color-picker-android#43]
When colorpicker_showAlpha is set to false and colorpicker_showHex is set to true deleting of text results in transparent color.

Workaround would be to apply the following color 
````
int color = shouldTrimAlphaDigits() ? 0xff000000 : 0;
````
in catch block of HexEdit.MultiObserver.onTextChanged instead of zero.

**Comment by martin-stone** [comment]
Thanks for reporting that. Will fix for the next release.

**Comment by martin-stone** [comment]
Fixed in version 2.3.1.
