### ISSUE TITLE
public constructor for ObservableColor

### ISSUE THREAD

**Issue by fazjaxton** [martin-stone/hsv-alpha-color-picker-android#48]
I am trying to use the individual views directly in my own custom layout.  However, I am unable to make an ObservableColor to link them together because the constructor is package-private.  ("cannot be accessed from outside package")  Could the constructor be made public for this use-case?

**Comment by martin-stone** [comment]
Done (version 2.4.2). I think the package scope was just an oversight.

It might make more sense for your use case to have a way of specifying a custom layout within the ColorPickerView. Then you wouldn't need to duplicate its functionality. E.g. If the view already had children it wouldn't inflate the R.layout.picker. More work though.

**Comment by fazjaxton** [comment]
Wow,  thanks!  Agreed that a way to customize ColorPickerView would be ideal.  I'll use them as components for now.
