### ISSUE TITLE
Set selected color

### ISSUE THREAD

**Issue by MFlisar** [martin-stone/hsv-alpha-color-picker-android#5]
Is that somehow possible? I don't want to set the start color but rather the manually selected color. So I can combine this view with a handful of fix colors, that update the selected color of the view if I click them so that the user can afterwards adjust that color (mainly the alpha).

I want to combine this color picker with the default palette colors...

**Comment by martin-stone** [comment]
I'll add a function for that in the next version. 

If you're in a hurry, you might be able to cheat by accessing the hex edit field and setting the value for the color you want (untested):

```
EditText hexEdit = (EditText)colorPickerView.findViewById(com.rarepebble.colorpicker.R.id.hexEdit);
hexEdit.setText(Integer.toHexString(color));
```

Alternatively, compile the library locally and add a function similar to [setColor()](https://github.com/martin-stone/hsv-alpha-color-picker-android/blob/master/colorpicker/src/main/java/com/rarepebble/colorpicker/ColorPickerView.java#L64) that omits the call to `swatchView.setOldColor()`.

**Comment by martin-stone** [comment]
In version 1.3 you can call setCurrentColor() to do what you need.
