### ISSUE TITLE
java.lang.ClassCastException: com.rarepebble.colorpicker.ColorPreference cannot be cast to androidx.preference.Preference

### ISSUE THREAD

**Issue by ployt0** [martin-stone/hsv-alpha-color-picker-android#52]
This isn't yet compatible with androidx, so it cannot be part of an androidx/preference/PreferenceScreen.java

**Comment by martin-stone** [comment]
Use [version 3](https://github.com/martin-stone/hsv-alpha-color-picker-android/tree/support-lib-preferences) (Currently on a branch, but will soon be merged to master.) I'm using it successfully in an AndroidX project. Note that there's an extra *onDisplayPreferenceDialog* integration needed, which is covered in the readme on the branch.

**Comment by ployt0** [comment]
Lint still complains:
![image](https://user-images.githubusercontent.com/25666053/64905513-7753cb80-d6d1-11e9-82ed-a6425d6c000a.png)
and the `PreferenceScreen` still crashes, only now with:
    android.view.InflateException: Binary XML file line #31: Error inflating class (not found)com.skydoves.colorpickerview.ColorPickerView

**Comment by ployt0** [comment]
Lint doesn't like it
![image](https://user-images.githubusercontent.com/25666053/64905568-3314fb00-d6d2-11e9-9b84-7253d7b38604.png)
and it still crashes, only now with: android.view.InflateException: Binary XML file line #31: Error inflating class (not found)com.skydoves.colorpickerview.ColorPickerView

**Comment by martin-stone** [comment]
PS: You may need to set [android.enableJetifier=true](https://developer.android.com/jetpack/androidx/migrate#migrate_an_existing_project_using_android_studio) in your gradle.properties if you haven't already.

**Comment by yvolk** [comment]
@ployt0 I did the Color Picker migration to AndroidX in my own repo, see https://github.com/martin-stone/hsv-alpha-color-picker-android/issues/54
