### ISSUE TITLE
Migrate to AndroidX

### ISSUE THREAD

**Issue by yvolk** [martin-stone/hsv-alpha-color-picker-android#54]
As I understand https://developer.android.com/guide/topics/ui/settings.html we should use AndroidX libraries for new development.

@martin-stone  Having your Color Picker as an internal project ( see https://github.com/martin-stone/hsv-alpha-color-picker-android/issues/51#issuecomment-524622055 ) I realized that before starting to write my new Custom preference I must migrate your component first :-)

And I did this. One day - and it works! Please feel free to integrate these changes into your repository, see this commit with full code of Preferences migration to AndroidX: https://github.com/andstatus/todoagenda/commit/27cce2c0a0fcddfe22ce71efd86b88d04020c7b2

@martin-stone Thank you once again for the beautiful Color Picker.

**Comment by martin-stone** [comment]
You can use this library with AndroidX without any changes by setting android.enableJetifier=true in your gradle.properties. At some point I'll migrate it fully, but right now the library supports apps using AndroidX and as well as those that have not yet migrated.
