### ISSUE TITLE
Dark Theme how to implement

### ISSUE THREAD

**Issue by vulterey** [martin-stone/hsv-alpha-color-picker-android#55]
Hi,

I am trying to use your color picker in the preference screen, but I cannot make it apear in Dark version as it shown in the demo app. Is there any extra setting which I miss to add to my root_preferences.xml file?

Kind Regards

Adam

**Comment by vulterey** [comment]
Found it ;)

In the:

    public static class SettingsFragment extends PreferenceFragmentCompat {
        @Override
        public void onCreatePreferences(Bundle savedInstanceState, String rootKey) {

Instead of:
              setPreferencesFromResource(R.xml.root_preferences, rootKey);
I should use:
              addPreferencesFromResource(R.xml.root_preferences);

        }

**Comment by martin-stone** [comment]
Glad you worked it out. (I wasn't sure where I'd start debugging this -- It has simply behaved as expected for me.)

**Comment by vulterey** [comment]
> Glad you worked it out. (I wasn't sure where I'd start debugging this -- It has simply behaved as expected for me.)

Thank you for quick reply. BTW very nice color picker and a good manual for installation.
