### ISSUE TITLE
jcenter()

### ISSUE THREAD

**Issue by vulterey** [martin-stone/hsv-alpha-color-picker-android#58]
Hi Martin,

Is there any chance you will migrate repository from jcenter to mavenCentral soon?

Kind Regards
Adam

**Comment by martin-stone** [comment]
Hi. Yes, that's the plan. I now have a sonatype account, but haven't had time to update [the publish script](https://github.com/martin-stone/hsv-alpha-color-picker-android/blob/master/colorpicker/bintray.gradle).

**Comment by vulterey** [comment]
Hi Martin,
 
Thank you for your prompt answer.
Let me know when you do it, please.

Regards

Adam

BTW: Random question. Where or in which app/software you created your avatar? It looks really well made.

**Comment by martin-stone** [comment]
It's stolen from some game art -- so would have been hand made by somebody with some artistic talent :-)

**Comment by vulterey** [comment]
Well, it is very persuading. I pictured you exactly like on this avatar ;) Thank you for your reply.

**Comment by martin-stone** [comment]
Let's leave this issue open, to reflect the status of the task.

**Comment by martin-stone** [comment]
Hi @vulterey. I've looked into Maven Central publishing and it involves a whole new set of dependencies that I'd rather not get entangled with, however JitPack seems to "just work". Could that be a solution for you? It's just a couple of changes to your build.gradle, documented in [the updated Readme](https://github.com/martin-stone/hsv-alpha-color-picker-android/pull/59/files). Can you try it and confirm that it works for you? (It works effortlessly for me on my dependent project.)

**Comment by vulterey** [comment]
Hi Martin,

Just tried to change my gradle file:
Below part of my gradle:
...
repositories {
    google()
    mavenCentral()
    maven { url "https://jitpack.io" }
}

dependencies {
    implementation 'com.github.martin-stone:hsv-alpha-color-picker-android:3.0.1'
...

Build failed:

Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.rarepebble:colorpicker:3.0.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/rarepebble/colorpicker/3.0.1/colorpicker-3.0.1.pom
       - https://repo.maven.apache.org/maven2/com/rarepebble/colorpicker/3.0.1/colorpicker-3.0.1.pom
       - https://jitpack.io/com/rarepebble/colorpicker/3.0.1/colorpicker-3.0.1.pom
     Required by:
         project :app

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by vulterey** [comment]
I removed mavenCentral() and there is a small improvement, but still no luck.
Build finished but with a warning:

Failed to resolve: com.rarepebble:colorpicker:3.0.1
Show in Project Structure dialog
Affected Modules: app

**Comment by vulterey** [comment]
Got it right ;D

Steps:

In your gradle file:

1. Remove from the dependencies section the line (if exists): 
_implementation 'com.rarepebble:colorpicker:3.0.1'_

2. Remove from the repositories section the line (if exists):
_jcenter()_

3. Add to the dependencies section the line:
**implementation 'com.github.martin-stone:hsv-alpha-color-picker-android:3.0.1'**

4. Add to the repositories section the line:
**maven { url "https://jitpack.io" }**

Example of the part of the gradle file:

...
repositories {
    google()
    **maven { url "https://jitpack.io" }**
}

dependencies {
    **implementation 'com.github.martin-stone:hsv-alpha-color-picker-android:3.0.1'**
    implementation fileTree(dir: 'libs', include: ['*.jar'])
...

I hope it will help others ;)

**Comment by martin-stone** [comment]
Glad you got it working. I'll update the readme with instructions to replace the old _com.rarepebble:colorpicker_ line (I'd been writing it from the perspective of a new user of the library.)

**Comment by vulterey** [comment]
Yes, it took me a while, but finally, I nailed it. Thank you very much for your quick help.

**Comment by ckhmer1** [comment]
Hello,
could You please upload also version 2 to mavenCentral?
I prefer it because it has fewer dependencies from the google libraries, and I don't use the androidx library to save space in my utility to be as small as possible.

Thanks
Claudio

**Comment by martin-stone** [comment]
Hi @ckhmer1. Version 2 should also be usable via jitpack, as above. Have you tried it? (Pick any version number from the [releases list](https://github.com/martin-stone/hsv-alpha-color-picker-android/releases).

**Comment by ckhmer1** [comment]
Hi,
I'm sorry, I didn't try yet. 
I thought that the version 2 was not maintained anymore, i like It because it is quite smaller than the version 3, because doesn't depend by Android X.

Thanks again
Claudio
