### ISSUE TITLE
Alpha and Color scroller do not work in a ViewPager

### ISSUE THREAD

**Issue by MFlisar** [martin-stone/hsv-alpha-color-picker-android#6]
In a ViewPager, I can't use the color picker view, as it does not correctly consume the touch events and the pager underneath catches the touches and starts scrolling.

The main view is handling the touches correctly and consumes them completely.

**Comment by martin-stone** [comment]
Fixed in 1.3

**Comment by MFlisar** [comment]
works, thanks
