### ISSUE TITLE
Add support for PreferenceDataStore

### ISSUE THREAD

**Issue by malaire** [martin-stone/hsv-alpha-color-picker-android#61]
Currently this is hard-coded to use `SharedPreferences`. Please add support also for [`PreferenceDataStore`](https://developer.android.com/reference/androidx/preference/PreferenceDataStore) ([Using a custom data store](https://developer.android.com/develop/ui/views/components/settings/use-saved-values#custom-data-store)).

This would allow using alternative storage than `SharedPreferences`, e.g. `DataStore`.

**Comment by martin-stone** [comment]
I'd be happy to consider a pull request.

**Comment by malaire** [comment]
I've now learned that `PreferenceDataStore` doesn't support e.g. optional integers of protobuf, which is essential feature for me to save "no color" selection. And since `PreferenceDataStore` is in maintenance mode, this and other issues will likely never be fixed.

So basically `PreferenceDataStore` is quite useless to me.
