### ISSUE TITLE
Hex value does not update until hue slider is moved

### ISSUE THREAD

**Issue by psyren89** [martin-stone/hsv-alpha-color-picker-android#9]
![slider](https://cloud.githubusercontent.com/assets/2491530/9652104/e4cc2910-524a-11e5-8909-6be454026458.gif)

**Comment by martin-stone** [comment]
That's the "value" slider, and you've used it to choose black. The hex value has to stay at ff000000.

**Comment by psyren89** [comment]
Oh, right. My bad.

**Comment by martin-stone** [comment]
No worries. Nice GIF, by the way :-)
